/*
  Warnings:

  - A unique constraint covering the columns `[sgeNombre]` on the table `Permiso` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `sgeNombre` to the `Permiso` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "SgeNombre" AS ENUM ('RES_LAB_RESERVAR_CURSO_AUTO', 'RES_LAB_VER_RESERVAS_CURSO_AUTO', 'RES_LAB_REALIZAR_RESERVA_DISCRECIONAL', 'RES_LAB_CONFIRMAR_RESERVAS', 'RES_LAB_VER_TODO_RESERVAS', 'RES_LAB_VER_RESERVAS_GENERALES_DOCENTES', 'RES_LAB_RESERVAR_CATEDRA_AUTO', 'RES_LAB_VER_RESERVAS_CATEDRA', 'APLICACIONES_VER_LISTADO', 'APLICACIONES_ABM', 'APLICACIONES_CARGAR_PRACTICA_AUTO', 'LAB_ABIERTO_RESERVAR', 'LAB_ABIERTO_VER_MIS_RESERVAS', 'LAB_ABIERTO_VER_PLANILLA_TUTORES', 'LAB_ABIERTO_CONFIRMAR_RESERVAS', 'LAB_ABIERTO_SUSPENDER_ALUMNO', 'LAB_ABIERTO_DESSUSPENDER_ALUMNO', 'LAB_ABIERTO_TUTORES_ABM', 'MATERIAS_ABM', 'MATERIAS_VER_LISTADO', 'MATERIAS_ADMINISTRAR_CORRELATIVA', 'CURSOS_MOSTRAR_TODOS', 'CURSOS_ABM', 'CURSOS_VER_MIS_CURSOS_AUTO', 'DIVISIONES_ABM', 'DIVISIONES_VER_LISTADO', 'ARMARIOS_ABM', 'ESTANTES_ABM', 'EQUIPOS_ABM', 'EQUIPOS_VER_LISTADO', 'EQUIPOS_BUSCAR_EQUIPO', 'EQUIPOS_REPORTE_ARMARIO', 'EQUIPOS_REPORTE_TIPO', 'EQUIPOS_ADMIN_VER_UBICACION', 'EQUIPOS_REPORTE_LABORATORIO', 'EQUIPOS_ABM_MANUALES', 'EQUIPOS_PRESTAMO_PRESTAR', 'EQUIPOS_PRESTAMO_VER_PRESTAMOS', 'EQUIPOS_PRESTAMO_VER_MIS_PRESTAMOS', 'EQUIPOS_TIPO_ABM', 'BIBLIOTECA_ABM_LIBRO', 'BIBLIOTECA_VER_LISTADO', 'BIBLIOTECA_BUSCAR_LIBRO', 'BIBLIOTECA_VER_DETALLES_LIBRO', 'BIBLIOTECA_EDITORIALES_ABM', 'BIBLIOTECA_PRESTAMO_PRESTAR', 'BIBLIOTECA_PRESTAMO_VER_PRESTAMOS', 'BIBLIOTECA_PRESTAMO_VER_MIS_PRESTAMOS', 'CONV_ELECTROCOMPONENTES_REQUERIR_CERTIFICADO', 'CONV_ELECTROCOMPONENTES_VER_DETALLES', 'CONV_ELECTROCOMPONENTES_ADMIN_CERTIFICADOS', 'CONV_ELECTROCOMPONENTES_ELIMINAR_CERTIFICADO', 'CONV_MAYER_REQUERIR_CERTIFICADO', 'CONV_MAYER_VER_MIS_PEDIDOS', 'CONV_MAYER_ENVIAR_RESUMEN', 'CONV_MAYER_ADMIN_PEDIDOS', 'REP_FALLAS_BUSCAR_REP_FALLAS', 'REP_FALLAS_REPORTAR_FALLAS', 'REP_FALLAS_ADMIN_REP_FALLAS', 'ACTIVIDADES_USUARIO_SGE_PUBLICAR_ADMIN', 'ACTIVIDADES_USUARIO_SGE_VER_PUBLICACIONES', 'ACTIVIDADES_ABIERTAS_PUBLICAR_ADMIN', 'ACTIVIDADES_ABIERTAS_VER_PUBLICACIONES', 'ADMIN_ACTUALIZAR_ACTA_CONSEJEROS', 'ADMIN_MODIFICAR_ATRIBUTOS', 'ADMIN_MODIFICAR_ATRIBUTOS_ADMIN', 'ADMIN_VER_PANEL_ADMIN', 'ADMIN_VER_RESULTADOS_ACTA', 'ADMIN_VER_NOTIFICACIONES_INDEX', 'ADMIN_ACCESO_SVN', 'ADMIN_VER_FICHA_USUARIO', 'ADMIN_AGREGAR_USUARIOS_A_GRUPOS', 'ADMIN_OFERTAS_LABORALES_ABM', 'RES_LAB_ABM_PANTALLA');

-- AlterTable
ALTER TABLE "Permiso" ADD COLUMN     "sgeNombre" "SgeNombre" NOT NULL;

-- CreateIndex
CREATE INDEX "Permiso_sgeNombre_idx" ON "Permiso"("sgeNombre");

-- CreateIndex
CREATE UNIQUE INDEX "Permiso_sgeNombre_key" ON "Permiso"("sgeNombre");
