services:
  db:
    image: postgres:17-alpine
    hostname: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    env_file:
      - ../.env
    volumes:
      - ../data:/var/lib/postgresql/data
      - ../dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sge2

  app:
    image: registry.frba.utn.edu.ar/ext/sge2
    env_file:
      - ../.env
    hostname: app
    networks:
      - sge2
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - sge2
    depends_on:
      - app

networks:
  sge2:
